"""
Django settings for school_one project.

Generated by 'django-admin startproject' using Django 5.2.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-&kgls@5h)3!lc95nh7k!+fldrm_h(^yj_o*oqj#b!!cez^ox57'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []

# Application definition

INSTALLED_APPS = [
    'jazzmin',  # Theme
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'apps.core',
    'apps.students',
    'apps.teachers'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'school_one.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'school_one.wsgi.application'

# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    # Shared platform databases for auth, groups, permissions
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'db_school_one',
        'USER': 'postgres',
        'PASSWORD': 'rxw121706#',
        'HOST': 'localhost',
        'PORT': '5432',
    },
    # 'school_abc': {
    #     'ENGINE': 'django.db.backends.postgresql',
    #     'NAME': 'abc_db',
    #     'USER': 'abc_user',
    #     'PASSWORD': 'abc_pass',
    #     'HOST': 'localhost',
    #     'PORT': '5432',
    # },
    # 'school_xyz': {
    #     'ENGINE': 'django.db.backends.postgresql',
    #     'NAME': 'xyz_db',
    #     'USER': 'xyz_user',
    #     'PASSWORD': 'xyz_pass',
    #     'HOST': 'localhost',
    #     'PORT': '5432',
    # },
    'school_test': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'db_school_test',
        'USER': 'postgres',
        'PASSWORD': 'rxw121706#',
        'HOST': 'localhost',
        'PORT': '5432',
    },
    # Add dynamically as you onboard schools
}

DATABASE_ROUTERS = [
    'school_one.auth_routers.AuthRouter',  # Handles shared data models(always comes first in the list)
    'school_one.db_router.SchoolDBRouter',  # Handles school-specific models
]

MIDDLEWARE += ['school_one.middleware.SchoolDBMiddleware']

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
