name: CI/CD Docker Deploy

on:
  push:
    branches:
      - dev
      - prod

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Build Docker image
      run: docker build -t rmdocker121/oneschool:${{ github.ref_name }} .

    - name: Push Docker image
      run: docker push rmdocker121/oneschool:${{ github.ref_name }}

    - name: Setup SSH
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.HOSTINGER_SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -H ${{ secrets.HOSTINGER_SSH_HOST }} >> ~/.ssh/known_hosts

    - name: Deploy on VPS
      run: |
        ssh ${{ secrets.HOSTINGER_SSH_USERNAME }}@${{ secrets.HOSTINGER_SSH_HOST }} "
          cd /home/youruser/oneschool &&
          git pull origin ${{ github.ref_name }} &&
          docker-compose down &&
          docker-compose up -d --build
        "
#      run: |
#        ssh ${{ secrets.HOSTINGER_SSH_USERNAME }}@${{ secrets.HOSTINGER_SSH_HOST }} "
#          docker pull rmdocker121/oneschool:${{ github.ref_name }} &&
#          docker stop oneschool || true &&
#          docker rm oneschool || true &&
#          docker run -d --name oneschool -p 80:8000 rmdocker121/oneschool:${{ github.ref_name }}
#        "